- name: Download Google Chrome .deb package
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome.deb

- name: Install Google Chrome
  apt:
    deb: /tmp/google-chrome.deb
    state: present

- name: Clean up
  file:
    path: /tmp/google-chrome.deb
    state: absent 
  become: true
  become_method: sudo