
- name: "Cloning Latest Repo Kerbrute"
  git:
    repo: "https://github.com/ropnop/kerbrute"
    dest: "/tmp/kerbrute"

- name: "Building Kerbrute"
  shell: |
        cd /tmp/kerbrute
        go build 

- name: "Move Kerbrute to bin"
  copy:
    src: "/tmp/kerbrute/kerbrute"
    dest: "{{ ansible_env.HOME }}/"
    mode: 0750
    
    