# tasks file for install-tools
- name: "Install dconf"
  apt: 
   name: dconf-cli
   state: latest
  become: true
  become_method: sudo

- name: "Install Go"
  include_tasks: "go-lang.yaml"

- name: "Install kerbrute"
  include_tasks: "kerbrute.yaml"

- name: "Install Google Chrome"
  include_tasks: "google.yaml"

- name: "Install VS Code"
  include_tasks: "vs_code.yaml"

- name: "Install snmp-mibs-downloader"
  include_tasks: "snmp-mibs.yaml"

  