
    - name: Install dependencies
      apt:
        name: 
          - software-properties-common
          - apt-transport-https
          - wget
        state: present
      become: true
      become_method: sudo        

    - name: Add VS Code repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
      become: true
      become_method: sudo

    - name: Update package list
      apt:
        update_cache: yes
      become: true
      become_method: sudo

    - name: Install VS Code
      apt:
        name: code
        state: present
      become: true
      become_method: sudo

    - name: Install VS Code extensions
      shell: |
        code --install-extension ms-python.python
        code --install-extension ms-python.vscode-pylance
        code --install-extension ms-python.debugpy
        code --install-extension GitHub.copilot
        code --install-extension GitHub.copilot-chat
        code --install-extension snyk-security.snyk-vulnerability-scanner
        code --install-extension ms-toolsai.jupyter
        code --install-extension ms-vscode.cpptools
        code --install-extension ms-vscode.csharp
        code --install-extension redhat.java
        code --install-extension golang.go