
 
    - name: Download VS Code .deb package
      get_url:
        url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
        dest: /tmp/code.deb

    - name: Install VS Code
      apt:
        deb: /tmp/code.deb
        state: present

    - name: Clean up
      file:
        path: /tmp/code.deb
        state: absent 
      become: true
      become_method: sudo

    - name: Install VS Code extensions
      shell: |
        code --install-extension ms-python.python
        code --install-extension ms-python.vscode-pylance
        code --install-extension ms-python.debugpy
        code --install-extension GitHub.copilot
        code --install-extension GitHub.copilot-chat
        code --install-extension snyk-security.snyk-vulnerability-scanner
        code --install-extension ms-toolsai.jupyter
        code --install-extension ms-vscode.cpptools
        code --install-extension ms-vscode.csharp
        code --install-extension redhat.java
        code --install-extension golang.go
      become: true
      become_user: kali