---
- name: "Customizing System"
  hosts: localhost
  connection: locale
  tasks:
    - name: "Demo Debug"
      debug:
        msg: "Hello world"

    - name: "Demo Copy"
      copy:
        src: "{{ playbook_dir }}/files/please-subscribe"
        dest: "/dev/shm/"
  
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/install-tools"
    # - role: gantsign.visual-studio-code
    #   users:
    #     - username: "{{ ansible_user_id }}"
    #       visual_studio_code_extensions:
    #         - streetsidesoftware.code-spell-checker
    #         - ms-python.python
    #         - snyk-security.snyk-vulnerability-scanner
    #         - Codeium.codeium